### ISSUE TITLE
docs/workflows/metadata.md Needs a bit more detail

### ISSUE THREAD

**Issue by matthewpeterkort** [ACED-IDP/aced-idp.github.io#14]
There should be 2-3 more examples for how a researcher can add metadata to a project. 
https://github.com/ACED-IDP/aced-idp.github.io/blob/feature/git-lite/docs/workflows/metadata.md

```
g3t add myfile.cram  --patient P0 --specimen P0-BoneMarrow --task_id P0-Sequencing
g3t utilities meta create 
```
^^ This is good but it's unclear what "g3t utilities meta create" does. Assuming that it creates ResearchStudy/Documentreferences if no metadata specific flags are added to `g3t add myfile.cram` but this should crystal clear for the end user reading the docs.

Also if diagnostic reports or observations can be added in same `--patient P0` like style above, then this should also be communicated. This is probably not the case, but It is unclear to the end user weather this meta create command can also create observations and diagnostic reports since there is no example code showing that is can be done.

The end user should know exactly how the gen3_util can assist them with metadata creation, ie: what the gen3_util can do for them and what they must do for gen3.

**Comment by bwalsh** [comment]
Thanks.   
See diagram here. https://deploy-preview-13--luminous-boba-a6e270.netlify.app/workflows/metadata/#create-metadata-files

Does this help?

**Comment by matthewpeterkort** [comment]
> @matthewpeterkort Thanks. See diagram here. https://deploy-preview-13--luminous-boba-a6e270.netlify.app/workflows/metadata/#create-metadata-files
> 
> Does this help?
Ok. See what you did here with the metadata generation. Probably doesn't need too many more docs. Didn't realize that codeable concepts don't have any required fields, so all you had to do was add a text entry under "code" and it could be a valid observation.
