### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by lbeckman314** [ACED-IDP/aced-idp.github.io#3]
## Proposed Changes

Not clear xargs
when to use xargs for all files in a directory
as opposed to individual files
http://localhost:8181/use-cases/use-case-3/#add-files-to-the-manifest

"Add this to mainfest"
Use this one for all files in directory
Use this one for specific ones

Replace 'Study' -> 'Project'

Sections:
- Upload
- Download

"Edge Cases"
- Restrict access
- Edit Project (adding files to project)

- [ ] Add steps for adding a user to the [Getting Started](https://aced-idp.github.io/getting-started/) section
- [ ] Update [Usage](https://aced-idp.github.io/requirements/#usage) tables with examples, steps for using env vars
- [ ] Add "General/Basic" file upload section (model after [Second Use Case](https://aced-idp.github.io/use-cases/use-case-2/)?) 
- [ ] Update screenshots with https://aced-idp.org
- [ ] Test Microsoft/Linux steps (check `source` commands compatibility)
- [ ] Write plan on merging/deprecating our gen3-client fork when multipart updates are pulled in upstream
- [ ] Add link checker to mkdocs to verify links work (https://github.com/byrnereese/linkchecker-mkdocs)
- [x] Investigate double checksums in [gen3-client's checksums.txt](https://github.com/ACED-IDP/cdis-data-client/releases)?

Thanks @jordan2lee for the pointers and recommendations on this!

**Comment by bwalsh** [comment]
@lbeckman314 is this still applicable?   if not, can you close?  thanks
