### ISSUE TITLE
Data Model Documentation

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/aced-idp.github.io#4]
From today's discussion:

`Notes to bootstrap the documentation`

# ACED data model
## Introduction

`TODO: this whole section`
Notes: 
* We define all our metadata as FHIR resources.  
* Metadata composition happens on the client
* There is a workflow

##  FHIR graph model

Examine [resource](https://www.hl7.org/fhir/resource.html) definitions [here](http://www.hl7.org/fhir/resource.html):
* Details on [uploaded files](https://aced-idp.github.io/workflows/upload/) are captured as [DocumentReference](http://www.hl7.org/fhir/documentreference.html)
* DocumentReference.[subject](https://www.hl7.org/fhir/documentreference-definitions.html#DocumentReference.subject) indicates who or what the document is about: 
  * Can simply point to the [ResearchStudy](https://hl7.org/fhir/researchstudy.html), to indicate the file is part of the study
  * Can point to [Patient](https://hl7.org/fhir/patient.html), or [Specimen](https://hl7.org/fhir/specimen.html), to indicate the file is based on them
* An [Observation](https://hl7.org/fhir/observation.html) can point to any entity    
* A [Task](https://hl7.org/fhir/task.html) can provide [provenance](https://en.wikipedia.org/wiki/Provenance#Data_provenance) on how the file was created 

Each resource has at least one study controlled [official](https://hl7.org/fhir/codesystem-identifier-use.html#identifier-use-official) [Identifier](https://hl7.org/fhir/datatypes.html#Identifier).  Child resources have [Reference](http://www.hl7.org/fhir/references.html) fields to point to their parent.

<img width="673" alt="image" src="https://github.com/ACED-IDP/aced-idp.github.io/assets/47808/801cfb7a-bff3-4c4f-97be-acba79830787">

### ResearchStudy
> A scientific study of nature that sometimes includes processes involved in health and disease.
[More](https://hl7.org/fhir/researchstudy.html)

### ResearchSubject
> A ResearchSubject is a participant or object which is the recipient of investigative activities in a research study.
[More](https://hl7.org/fhir/researchsubject.html)

### Patient 
> Demographics and other administrative information about an individual or animal receiving care or other health-related services.
[More](https://hl7.org/fhir/patient.html)

### Specimen

> A sample to be used for analysis.
[More](https://hl7.org/fhir/specimen.html)

### DocumentReference
> A reference to a document of any kind for any purpose. 
[More](https://hl7.org/fhir/documentreference.html)

## Identifiers

> A string, typically numeric or alphanumeric, that is associated with a single object or entity within a given system. Typically, identifiers are used to connect content in resources to external content available in other frameworks or protocols.

[More](https://hl7.org/fhir/datatypes.html#Identifier)

## References

> Many of the defined elements in a resource are references to other resources. Using these references, the resources combine to build a web of information about healthcare.

[More](https://hl7.org/fhir/references.html)

## CodeSystems (Ontologies)

> The Fast Healthcare Interoperability Resources (FHIR) standard defines a set of terminology resources that provide a mechanism to access clinical terminology in a standardised way. Many clinical terminologies are currently supported, including SNOMED CT, RxNorm and LOINC. Recently, there has been increasing interest in supporting terminologies from other domains. In genomics, for example, there is increasing use of the Human Phenotype Ontology (HPO)[1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7153051/#r1-3202087) to capture information about rare diseases. 
 
[PMID: 32308861](https://pubmed.ncbi.nlm.nih.gov/32308861/)

[SNOMED](https://build.fhir.org/snomedct-usage.html):
While there are [many possible uses of snomed](https://build.fhir.org/snomedct-usage.html) in the entire FHIR model, our focus is on these fields:
* [Specimen.collection.bodySite](https://build.fhir.org/specimen-definitions.html#Specimen.collection.bodySite)
* [Condition.bodySite](https://build.fhir.org/condition-definitions.html#Condition.bodySite)
* [Substance.code](https://build.fhir.org/valueset-substance-code.html) `TODO: pubchem?`

[MONDO](https://terminology.hl7.org/CodeSystem-MONDO.html):
* [Condition.code](https://build.fhir.org/condition-definitions.html#Condition.code)

[Other: `TODO`]():
* TODO

## Happy path
  * `TODO` As an ACED user, in order to contribute data, I need docs, code and examples on how to populate spreadsheets, validate and submit data.

## Workflow 
   * `TODO` Use synthetic data as an example

**Comment by bwalsh** [comment]
See http://gb2.clinfhir.com/


[my test project-Example view-fsh.fsh.txt](https://github.com/ACED-IDP/aced-idp.github.io/files/13592900/my.test.project-Example.view-fsh.fsh.txt)
[my test project-Example view.json](https://github.com/ACED-IDP/aced-idp.github.io/files/13592910/my.test.project-Example.view.json)

**Comment by matthewpeterkort** [comment]
Probably Also worth it to mention LOINC codes? Also, This seems like good bare bones, but a new data model user might need some more context on FHIR before pointing them to many FHIR docs pages.  Will try to contribute to this a bit in the coming days.
